spring.application.name=catalog


spring.datasource.url=jdbc:sqlite:catalog.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update


jwt.secret=9xK2mP7vQ4w_XzL8jRtB2fY1hC6dFn3pG0sK5xQ9vW4
jwt.expiration-ms=86400000